name: Build and Release Assets

on:
  release:
    types: [created]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive build artifacts
        run: |
          cd dist
          zip -r ../komari-Taca.zip .
          cd ..

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./komari-Taca.zip
          asset_name: komari-Taca.zip
          asset_content_type: application/zip
